# Generated by Django 4.1.7 on 2023-03-18 22:40

from django.db import migrations, models
import file_uploader.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=file_uploader.models.user_directory_path
                    ),
                ),
            ],
        ),
    ]
